name: TYPO3 TER Upload

on:
  push:
    tags:
      - "**"

jobs:
  TERUpload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: composer --version
      - run: composer prepare-release -vvv
      - uses: tomasnorre/typo3-upload-ter@v2.2.1
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
          php-version: 8.3
